FarLeft = "Far_Left"
Left = "Left"
Neutral = "Neutral"
Right = "Right"
FarRight = "Far_Right"

Male = "Male"
Female = "Female"

JoeBiden = "Joe_Biden"
BarrackObama = "Barrack_Obama"
BernieSanders = "Bernie_Sanders"
DonaldTrump = "Donald_Trump"
JohnMccain = "John_Mccain"
HillaryClinton = "Hillary_Clinton"
BetsyDevos = "Betsy_Devos"
ElizabethWarren = "Elizabeth_Warren"
AlexandriaOcasioCortez = "Alexandria_ocasio-cortez"
SarahPalin = "Sarah_Palin"